global:
  scrape_interval: 10s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost']
  - job_name: 'otterspace-api-staging'
    scrape_interval: 30s
    metrics_path: '/metrics'
    scheme: https
    static_configs:
      - targets: ['otterspace-api-staging.herokuapp.com']