global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost']
  - job_name: 'prometheus-otterspace-api'
    scrape_interval: 2m
    metrics_path: '/metrics'
    scheme: https
    static_configs:
      - targets: ['otterspace-api-staging.herokuapp.com']